# Generated by Django 5.2.3 on 2025-07-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Optional. Linked prescription for auto-reminders.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinical.prescription'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(help_text='Time when the notification should be triggered.'),
        ),
    ]
