# Generated by Django 5.2.4 on 2025-08-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_update_notification_model"),
        ("notification", "0003_notification_send_to_all_alter_notification_patient"),
    ]

    operations = []
