# Generated by Django 5.2.4 on 2025-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_merge_20250802_2302"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_patient_2ee12b_idx",
            old_name="notification_patient_2b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_a5f01d_idx",
            old_name="notification_notifica_8c8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_created_fcd7aa_idx",
            old_name="notification_created_8c8c8c_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(default=True),
        ),
    ]
