# Generated by Django 5.2.3 on 2025-07-23 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0004_alter_appointment_department_alter_doctor_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('medicines', models.TextField(help_text='Medicine names with dosage and timing instructions.')),
                ('prescribed_date', models.DateField(auto_now_add=True)),
                ('reminder_time', models.TimeField(help_text='Time of day patient should take the medicine.')),
                ('reminder_start_date', models.DateField(help_text='When should reminders start?')),
                ('reminder_end_date', models.DateField(help_text='When should reminders stop?')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
