# Generated by Django 5.2.4 on 2025-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_doctor_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pulmonology', 'Pulmonology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology')], max_length=100),
        ),
    ]
