# Generated by Django 5.2.3 on 2025-07-31 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagepurchase',
            name='chosen_date',
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='selected_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='duration_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='payment_status',
            field=models.CharField(default='Success', max_length=20),
        ),
    ]
