# Generated by Django 5.2.4 on 2025-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0002_remove_packagepurchase_chosen_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagepurchase",
            name="patient_details",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
