# Generated by Django 5.2.4 on 2025-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0008_user_blood_group_emergency_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alcohol_consumption",
            field=models.CharField(
                blank=True,
                help_text="Alcohol consumption status",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allergies",
            field=models.TextField(
                blank=True, help_text="List of allergies", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blood_pressure",
            field=models.CharField(
                blank=True, help_text="Blood pressure reading", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_medications",
            field=models.TextField(
                blank=True, help_text="Current medications being taken", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="diabetes_status",
            field=models.CharField(
                blank=True, help_text="Diabetes status", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="family_history",
            field=models.TextField(
                blank=True, help_text="Family medical history", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.CharField(
                blank=True, help_text="Height in cm", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lifestyle_info",
            field=models.TextField(
                blank=True, help_text="Lifestyle information", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="Current medical conditions", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="smoking_status",
            field=models.CharField(
                blank=True, help_text="Smoking status", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.CharField(
                blank=True, help_text="Weight in kg", max_length=10, null=True
            ),
        ),
    ]
