# Generated by Django 5.2.4 on 2025-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0009_user_alcohol_consumption_user_allergies_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="medical_conditions",
            new_name="chronic_conditions",
        ),
        migrations.AddField(
            model_name="user",
            name="surgeries",
            field=models.TextField(
                blank=True, help_text="Previous surgeries", null=True
            ),
        ),
    ]
