# Generated by Django 5.2.4 on 2025-08-03 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_alter_medicinerequest_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinerequest",
            name="admin_comments",
            field=models.TextField(
                blank=True, help_text="Comments from admin for approval/rejection"
            ),
        ),
        migrations.AddField(
            model_name="medicinerequest",
            name="prescription_file",
            field=models.FileField(
                blank=True,
                help_text="Upload prescription image (PNG, JPG only, max 5MB)",
                null=True,
                upload_to="prescriptions/medicine_requests/",
            ),
        ),
        migrations.AddField(
            model_name="medicinerequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicinerequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="medicinerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
